// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeatMessage.proto

#ifndef PROTOBUF_HeartBeatMessage_2eproto__INCLUDED
#define PROTOBUF_HeartBeatMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "InternalType.pb.h"
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_HeartBeatMessage_2eproto();
void protobuf_AssignDesc_HeartBeatMessage_2eproto();
void protobuf_ShutdownFile_HeartBeatMessage_2eproto();

class HeartBeatRequestMessage;
class HeartBeatResponseMessage;

// ===================================================================

class HeartBeatRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.HeartBeatRequestMessage) */ {
 public:
  HeartBeatRequestMessage();
  virtual ~HeartBeatRequestMessage();

  HeartBeatRequestMessage(const HeartBeatRequestMessage& from);

  inline HeartBeatRequestMessage& operator=(const HeartBeatRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatRequestMessage& default_instance();

  void Swap(HeartBeatRequestMessage* other);

  // implements Message ----------------------------------------------

  inline HeartBeatRequestMessage* New() const { return New(NULL); }

  HeartBeatRequestMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeatRequestMessage& from);
  void MergeFrom(const HeartBeatRequestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartBeatRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional string file_name_ = 3;
  void clear_file_name_();
  static const int kFileNameFieldNumber = 3;
  const ::std::string& file_name_() const;
  void set_file_name_(const ::std::string& value);
  void set_file_name_(const char* value);
  void set_file_name_(const char* value, size_t size);
  ::std::string* mutable_file_name_();
  ::std::string* release_file_name_();
  void set_allocated_file_name_(::std::string* file_name_);

  // optional uint32 split_id_ = 4;
  void clear_split_id_();
  static const int kSplitIdFieldNumber = 4;
  ::google::protobuf::uint32 split_id_() const;
  void set_split_id_(::google::protobuf::uint32 value);

  // optional .Imagine_MapReduce.Internal.TaskStatus task_status_ = 5;
  void clear_task_status_();
  static const int kTaskStatusFieldNumber = 5;
  ::Imagine_MapReduce::Internal::TaskStatus task_status_() const;
  void set_task_status_(::Imagine_MapReduce::Internal::TaskStatus value);

  // optional double task_progress_ = 6;
  void clear_task_progress_();
  static const int kTaskProgressFieldNumber = 6;
  double task_progress_() const;
  void set_task_progress_(double value);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.HeartBeatRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  ::google::protobuf::internal::ArenaStringPtr file_name__;
  ::google::protobuf::uint32 split_id__;
  int task_status__;
  double task_progress__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_HeartBeatMessage_2eproto();
  friend void protobuf_AssignDesc_HeartBeatMessage_2eproto();
  friend void protobuf_ShutdownFile_HeartBeatMessage_2eproto();

  void InitAsDefaultInstance();
  static HeartBeatRequestMessage* default_instance_;
};
// -------------------------------------------------------------------

class HeartBeatResponseMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.HeartBeatResponseMessage) */ {
 public:
  HeartBeatResponseMessage();
  virtual ~HeartBeatResponseMessage();

  HeartBeatResponseMessage(const HeartBeatResponseMessage& from);

  inline HeartBeatResponseMessage& operator=(const HeartBeatResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatResponseMessage& default_instance();

  void Swap(HeartBeatResponseMessage* other);

  // implements Message ----------------------------------------------

  inline HeartBeatResponseMessage* New() const { return New(NULL); }

  HeartBeatResponseMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeatResponseMessage& from);
  void MergeFrom(const HeartBeatResponseMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartBeatResponseMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  void clear_status_();
  static const int kStatusFieldNumber = 3;
  ::Imagine_MapReduce::Internal::Status status_() const;
  void set_status_(::Imagine_MapReduce::Internal::Status value);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.HeartBeatResponseMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  int status__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_HeartBeatMessage_2eproto();
  friend void protobuf_AssignDesc_HeartBeatMessage_2eproto();
  friend void protobuf_ShutdownFile_HeartBeatMessage_2eproto();

  void InitAsDefaultInstance();
  static HeartBeatResponseMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HeartBeatRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void HeartBeatRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity HeartBeatRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void HeartBeatRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void HeartBeatRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity HeartBeatRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void HeartBeatRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.recv_identity_)
}

// optional string file_name_ = 3;
inline void HeartBeatRequestMessage::clear_file_name_() {
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HeartBeatRequestMessage::file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
  return file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRequestMessage::set_file_name_(const ::std::string& value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
}
inline void HeartBeatRequestMessage::set_file_name_(const char* value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
}
inline void HeartBeatRequestMessage::set_file_name_(const char* value, size_t size) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
}
inline ::std::string* HeartBeatRequestMessage::mutable_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
  return file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartBeatRequestMessage::release_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
  
  return file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRequestMessage::set_allocated_file_name_(::std::string* file_name_) {
  if (file_name_ != NULL) {
    
  } else {
    
  }
  file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.HeartBeatRequestMessage.file_name_)
}

// optional uint32 split_id_ = 4;
inline void HeartBeatRequestMessage::clear_split_id_() {
  split_id__ = 0u;
}
inline ::google::protobuf::uint32 HeartBeatRequestMessage::split_id_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.split_id_)
  return split_id__;
}
inline void HeartBeatRequestMessage::set_split_id_(::google::protobuf::uint32 value) {
  
  split_id__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.split_id_)
}

// optional .Imagine_MapReduce.Internal.TaskStatus task_status_ = 5;
inline void HeartBeatRequestMessage::clear_task_status_() {
  task_status__ = 0;
}
inline ::Imagine_MapReduce::Internal::TaskStatus HeartBeatRequestMessage::task_status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.task_status_)
  return static_cast< ::Imagine_MapReduce::Internal::TaskStatus >(task_status__);
}
inline void HeartBeatRequestMessage::set_task_status_(::Imagine_MapReduce::Internal::TaskStatus value) {
  
  task_status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.task_status_)
}

// optional double task_progress_ = 6;
inline void HeartBeatRequestMessage::clear_task_progress_() {
  task_progress__ = 0;
}
inline double HeartBeatRequestMessage::task_progress_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatRequestMessage.task_progress_)
  return task_progress__;
}
inline void HeartBeatRequestMessage::set_task_progress_(double value) {
  
  task_progress__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatRequestMessage.task_progress_)
}

// -------------------------------------------------------------------

// HeartBeatResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void HeartBeatResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity HeartBeatResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void HeartBeatResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void HeartBeatResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity HeartBeatResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void HeartBeatResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
inline void HeartBeatResponseMessage::clear_status_() {
  status__ = 0;
}
inline ::Imagine_MapReduce::Internal::Status HeartBeatResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.HeartBeatResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
inline void HeartBeatResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.HeartBeatResponseMessage.status_)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_HeartBeatMessage_2eproto__INCLUDED
