// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReduceTaskMessage.proto

#ifndef PROTOBUF_ReduceTaskMessage_2eproto__INCLUDED
#define PROTOBUF_ReduceTaskMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "InternalType.pb.h"
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ReduceTaskMessage_2eproto();
void protobuf_AssignDesc_ReduceTaskMessage_2eproto();
void protobuf_ShutdownFile_ReduceTaskMessage_2eproto();

class ReduceTaskRequestMessage;
class ReduceTaskResponseMessage;

// ===================================================================

class ReduceTaskRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.ReduceTaskRequestMessage) */ {
 public:
  ReduceTaskRequestMessage();
  virtual ~ReduceTaskRequestMessage();

  ReduceTaskRequestMessage(const ReduceTaskRequestMessage& from);

  inline ReduceTaskRequestMessage& operator=(const ReduceTaskRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReduceTaskRequestMessage& default_instance();

  void Swap(ReduceTaskRequestMessage* other);

  // implements Message ----------------------------------------------

  inline ReduceTaskRequestMessage* New() const { return New(NULL); }

  ReduceTaskRequestMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReduceTaskRequestMessage& from);
  void MergeFrom(const ReduceTaskRequestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReduceTaskRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional string file_name_ = 3;
  void clear_file_name_();
  static const int kFileNameFieldNumber = 3;
  const ::std::string& file_name_() const;
  void set_file_name_(const ::std::string& value);
  void set_file_name_(const char* value);
  void set_file_name_(const char* value, size_t size);
  ::std::string* mutable_file_name_();
  ::std::string* release_file_name_();
  void set_allocated_file_name_(::std::string* file_name_);

  // optional string split_file_name_ = 4;
  void clear_split_file_name_();
  static const int kSplitFileNameFieldNumber = 4;
  const ::std::string& split_file_name_() const;
  void set_split_file_name_(const ::std::string& value);
  void set_split_file_name_(const char* value);
  void set_split_file_name_(const char* value, size_t size);
  ::std::string* mutable_split_file_name_();
  ::std::string* release_split_file_name_();
  void set_allocated_split_file_name_(::std::string* split_file_name_);

  // optional uint32 split_num_ = 5;
  void clear_split_num_();
  static const int kSplitNumFieldNumber = 5;
  ::google::protobuf::uint32 split_num_() const;
  void set_split_num_(::google::protobuf::uint32 value);

  // optional string mapper_ip_ = 6;
  void clear_mapper_ip_();
  static const int kMapperIpFieldNumber = 6;
  const ::std::string& mapper_ip_() const;
  void set_mapper_ip_(const ::std::string& value);
  void set_mapper_ip_(const char* value);
  void set_mapper_ip_(const char* value, size_t size);
  ::std::string* mutable_mapper_ip_();
  ::std::string* release_mapper_ip_();
  void set_allocated_mapper_ip_(::std::string* mapper_ip_);

  // optional string mapper_port_ = 7;
  void clear_mapper_port_();
  static const int kMapperPortFieldNumber = 7;
  const ::std::string& mapper_port_() const;
  void set_mapper_port_(const ::std::string& value);
  void set_mapper_port_(const char* value);
  void set_mapper_port_(const char* value, size_t size);
  ::std::string* mutable_mapper_port_();
  ::std::string* release_mapper_port_();
  void set_allocated_mapper_port_(::std::string* mapper_port_);

  // optional string master_ip_ = 8;
  void clear_master_ip_();
  static const int kMasterIpFieldNumber = 8;
  const ::std::string& master_ip_() const;
  void set_master_ip_(const ::std::string& value);
  void set_master_ip_(const char* value);
  void set_master_ip_(const char* value, size_t size);
  ::std::string* mutable_master_ip_();
  ::std::string* release_master_ip_();
  void set_allocated_master_ip_(::std::string* master_ip_);

  // optional string master_port_ = 9;
  void clear_master_port_();
  static const int kMasterPortFieldNumber = 9;
  const ::std::string& master_port_() const;
  void set_master_port_(const ::std::string& value);
  void set_master_port_(const char* value);
  void set_master_port_(const char* value, size_t size);
  ::std::string* mutable_master_port_();
  ::std::string* release_master_port_();
  void set_allocated_master_port_(::std::string* master_port_);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  ::google::protobuf::internal::ArenaStringPtr file_name__;
  ::google::protobuf::internal::ArenaStringPtr split_file_name__;
  ::google::protobuf::internal::ArenaStringPtr mapper_ip__;
  ::google::protobuf::internal::ArenaStringPtr mapper_port__;
  ::google::protobuf::internal::ArenaStringPtr master_ip__;
  ::google::protobuf::internal::ArenaStringPtr master_port__;
  ::google::protobuf::uint32 split_num__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ReduceTaskMessage_2eproto();
  friend void protobuf_AssignDesc_ReduceTaskMessage_2eproto();
  friend void protobuf_ShutdownFile_ReduceTaskMessage_2eproto();

  void InitAsDefaultInstance();
  static ReduceTaskRequestMessage* default_instance_;
};
// -------------------------------------------------------------------

class ReduceTaskResponseMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.ReduceTaskResponseMessage) */ {
 public:
  ReduceTaskResponseMessage();
  virtual ~ReduceTaskResponseMessage();

  ReduceTaskResponseMessage(const ReduceTaskResponseMessage& from);

  inline ReduceTaskResponseMessage& operator=(const ReduceTaskResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReduceTaskResponseMessage& default_instance();

  void Swap(ReduceTaskResponseMessage* other);

  // implements Message ----------------------------------------------

  inline ReduceTaskResponseMessage* New() const { return New(NULL); }

  ReduceTaskResponseMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReduceTaskResponseMessage& from);
  void MergeFrom(const ReduceTaskResponseMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReduceTaskResponseMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  void clear_status_();
  static const int kStatusFieldNumber = 3;
  ::Imagine_MapReduce::Internal::Status status_() const;
  void set_status_(::Imagine_MapReduce::Internal::Status value);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  int status__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ReduceTaskMessage_2eproto();
  friend void protobuf_AssignDesc_ReduceTaskMessage_2eproto();
  friend void protobuf_ShutdownFile_ReduceTaskMessage_2eproto();

  void InitAsDefaultInstance();
  static ReduceTaskResponseMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ReduceTaskRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void ReduceTaskRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity ReduceTaskRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void ReduceTaskRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void ReduceTaskRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity ReduceTaskRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void ReduceTaskRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.recv_identity_)
}

// optional string file_name_ = 3;
inline void ReduceTaskRequestMessage::clear_file_name_() {
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  return file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_file_name_(const ::std::string& value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
inline void ReduceTaskRequestMessage::set_file_name_(const char* value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
inline void ReduceTaskRequestMessage::set_file_name_(const char* value, size_t size) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  return file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  
  return file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_file_name_(::std::string* file_name_) {
  if (file_name_ != NULL) {
    
  } else {
    
  }
  file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}

// optional string split_file_name_ = 4;
inline void ReduceTaskRequestMessage::clear_split_file_name_() {
  split_file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::split_file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  return split_file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_split_file_name_(const ::std::string& value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
inline void ReduceTaskRequestMessage::set_split_file_name_(const char* value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
inline void ReduceTaskRequestMessage::set_split_file_name_(const char* value, size_t size) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_split_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  return split_file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_split_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  
  return split_file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_split_file_name_(::std::string* split_file_name_) {
  if (split_file_name_ != NULL) {
    
  } else {
    
  }
  split_file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), split_file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}

// optional uint32 split_num_ = 5;
inline void ReduceTaskRequestMessage::clear_split_num_() {
  split_num__ = 0u;
}
inline ::google::protobuf::uint32 ReduceTaskRequestMessage::split_num_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_num_)
  return split_num__;
}
inline void ReduceTaskRequestMessage::set_split_num_(::google::protobuf::uint32 value) {
  
  split_num__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_num_)
}

// optional string mapper_ip_ = 6;
inline void ReduceTaskRequestMessage::clear_mapper_ip_() {
  mapper_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::mapper_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  return mapper_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_mapper_ip_(const ::std::string& value) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
inline void ReduceTaskRequestMessage::set_mapper_ip_(const char* value) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
inline void ReduceTaskRequestMessage::set_mapper_ip_(const char* value, size_t size) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_mapper_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  return mapper_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_mapper_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  
  return mapper_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_mapper_ip_(::std::string* mapper_ip_) {
  if (mapper_ip_ != NULL) {
    
  } else {
    
  }
  mapper_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapper_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}

// optional string mapper_port_ = 7;
inline void ReduceTaskRequestMessage::clear_mapper_port_() {
  mapper_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::mapper_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  return mapper_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_mapper_port_(const ::std::string& value) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
inline void ReduceTaskRequestMessage::set_mapper_port_(const char* value) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
inline void ReduceTaskRequestMessage::set_mapper_port_(const char* value, size_t size) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_mapper_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  return mapper_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_mapper_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  
  return mapper_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_mapper_port_(::std::string* mapper_port_) {
  if (mapper_port_ != NULL) {
    
  } else {
    
  }
  mapper_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapper_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}

// optional string master_ip_ = 8;
inline void ReduceTaskRequestMessage::clear_master_ip_() {
  master_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::master_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  return master_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_master_ip_(const ::std::string& value) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
inline void ReduceTaskRequestMessage::set_master_ip_(const char* value) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
inline void ReduceTaskRequestMessage::set_master_ip_(const char* value, size_t size) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_master_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  return master_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_master_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  
  return master_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_master_ip_(::std::string* master_ip_) {
  if (master_ip_ != NULL) {
    
  } else {
    
  }
  master_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), master_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}

// optional string master_port_ = 9;
inline void ReduceTaskRequestMessage::clear_master_port_() {
  master_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ReduceTaskRequestMessage::master_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  return master_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_master_port_(const ::std::string& value) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
inline void ReduceTaskRequestMessage::set_master_port_(const char* value) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
inline void ReduceTaskRequestMessage::set_master_port_(const char* value, size_t size) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
inline ::std::string* ReduceTaskRequestMessage::mutable_master_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  return master_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReduceTaskRequestMessage::release_master_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  
  return master_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReduceTaskRequestMessage::set_allocated_master_port_(::std::string* master_port_) {
  if (master_port_ != NULL) {
    
  } else {
    
  }
  master_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), master_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}

// -------------------------------------------------------------------

// ReduceTaskResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void ReduceTaskResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity ReduceTaskResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void ReduceTaskResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void ReduceTaskResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity ReduceTaskResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void ReduceTaskResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
inline void ReduceTaskResponseMessage::clear_status_() {
  status__ = 0;
}
inline ::Imagine_MapReduce::Internal::Status ReduceTaskResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
inline void ReduceTaskResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.status_)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ReduceTaskMessage_2eproto__INCLUDED
