// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RetrieveSplitFileMessage.proto

#ifndef PROTOBUF_RetrieveSplitFileMessage_2eproto__INCLUDED
#define PROTOBUF_RetrieveSplitFileMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "InternalType.pb.h"
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_RetrieveSplitFileMessage_2eproto();
void protobuf_AssignDesc_RetrieveSplitFileMessage_2eproto();
void protobuf_ShutdownFile_RetrieveSplitFileMessage_2eproto();

class RetrieveSplitFileRequestMessage;
class RetrieveSplitFileResponseMessage;

// ===================================================================

class RetrieveSplitFileRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage) */ {
 public:
  RetrieveSplitFileRequestMessage();
  virtual ~RetrieveSplitFileRequestMessage();

  RetrieveSplitFileRequestMessage(const RetrieveSplitFileRequestMessage& from);

  inline RetrieveSplitFileRequestMessage& operator=(const RetrieveSplitFileRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RetrieveSplitFileRequestMessage& default_instance();

  void Swap(RetrieveSplitFileRequestMessage* other);

  // implements Message ----------------------------------------------

  inline RetrieveSplitFileRequestMessage* New() const { return New(NULL); }

  RetrieveSplitFileRequestMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RetrieveSplitFileRequestMessage& from);
  void MergeFrom(const RetrieveSplitFileRequestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RetrieveSplitFileRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional string split_file_name_ = 3;
  void clear_split_file_name_();
  static const int kSplitFileNameFieldNumber = 3;
  const ::std::string& split_file_name_() const;
  void set_split_file_name_(const ::std::string& value);
  void set_split_file_name_(const char* value);
  void set_split_file_name_(const char* value, size_t size);
  ::std::string* mutable_split_file_name_();
  ::std::string* release_split_file_name_();
  void set_allocated_split_file_name_(::std::string* split_file_name_);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  ::google::protobuf::internal::ArenaStringPtr split_file_name__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_RetrieveSplitFileMessage_2eproto();
  friend void protobuf_AssignDesc_RetrieveSplitFileMessage_2eproto();
  friend void protobuf_ShutdownFile_RetrieveSplitFileMessage_2eproto();

  void InitAsDefaultInstance();
  static RetrieveSplitFileRequestMessage* default_instance_;
};
// -------------------------------------------------------------------

class RetrieveSplitFileResponseMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage) */ {
 public:
  RetrieveSplitFileResponseMessage();
  virtual ~RetrieveSplitFileResponseMessage();

  RetrieveSplitFileResponseMessage(const RetrieveSplitFileResponseMessage& from);

  inline RetrieveSplitFileResponseMessage& operator=(const RetrieveSplitFileResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RetrieveSplitFileResponseMessage& default_instance();

  void Swap(RetrieveSplitFileResponseMessage* other);

  // implements Message ----------------------------------------------

  inline RetrieveSplitFileResponseMessage* New() const { return New(NULL); }

  RetrieveSplitFileResponseMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RetrieveSplitFileResponseMessage& from);
  void MergeFrom(const RetrieveSplitFileResponseMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RetrieveSplitFileResponseMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  void clear_status_();
  static const int kStatusFieldNumber = 3;
  ::Imagine_MapReduce::Internal::Status status_() const;
  void set_status_(::Imagine_MapReduce::Internal::Status value);

  // optional string split_file_content_ = 4;
  void clear_split_file_content_();
  static const int kSplitFileContentFieldNumber = 4;
  const ::std::string& split_file_content_() const;
  void set_split_file_content_(const ::std::string& value);
  void set_split_file_content_(const char* value);
  void set_split_file_content_(const char* value, size_t size);
  ::std::string* mutable_split_file_content_();
  ::std::string* release_split_file_content_();
  void set_allocated_split_file_content_(::std::string* split_file_content_);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  ::google::protobuf::internal::ArenaStringPtr split_file_content__;
  int status__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_RetrieveSplitFileMessage_2eproto();
  friend void protobuf_AssignDesc_RetrieveSplitFileMessage_2eproto();
  friend void protobuf_ShutdownFile_RetrieveSplitFileMessage_2eproto();

  void InitAsDefaultInstance();
  static RetrieveSplitFileResponseMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RetrieveSplitFileRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void RetrieveSplitFileRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity RetrieveSplitFileRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void RetrieveSplitFileRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void RetrieveSplitFileRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity RetrieveSplitFileRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void RetrieveSplitFileRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.recv_identity_)
}

// optional string split_file_name_ = 3;
inline void RetrieveSplitFileRequestMessage::clear_split_file_name_() {
  split_file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RetrieveSplitFileRequestMessage::split_file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
  return split_file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RetrieveSplitFileRequestMessage::set_split_file_name_(const ::std::string& value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
}
inline void RetrieveSplitFileRequestMessage::set_split_file_name_(const char* value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
}
inline void RetrieveSplitFileRequestMessage::set_split_file_name_(const char* value, size_t size) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
}
inline ::std::string* RetrieveSplitFileRequestMessage::mutable_split_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
  return split_file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RetrieveSplitFileRequestMessage::release_split_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
  
  return split_file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RetrieveSplitFileRequestMessage::set_allocated_split_file_name_(::std::string* split_file_name_) {
  if (split_file_name_ != NULL) {
    
  } else {
    
  }
  split_file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), split_file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.RetrieveSplitFileRequestMessage.split_file_name_)
}

// -------------------------------------------------------------------

// RetrieveSplitFileResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void RetrieveSplitFileResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity RetrieveSplitFileResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void RetrieveSplitFileResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void RetrieveSplitFileResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity RetrieveSplitFileResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void RetrieveSplitFileResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
inline void RetrieveSplitFileResponseMessage::clear_status_() {
  status__ = 0;
}
inline ::Imagine_MapReduce::Internal::Status RetrieveSplitFileResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
inline void RetrieveSplitFileResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.status_)
}

// optional string split_file_content_ = 4;
inline void RetrieveSplitFileResponseMessage::clear_split_file_content_() {
  split_file_content__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RetrieveSplitFileResponseMessage::split_file_content_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
  return split_file_content__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RetrieveSplitFileResponseMessage::set_split_file_content_(const ::std::string& value) {
  
  split_file_content__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
}
inline void RetrieveSplitFileResponseMessage::set_split_file_content_(const char* value) {
  
  split_file_content__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
}
inline void RetrieveSplitFileResponseMessage::set_split_file_content_(const char* value, size_t size) {
  
  split_file_content__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
}
inline ::std::string* RetrieveSplitFileResponseMessage::mutable_split_file_content_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
  return split_file_content__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RetrieveSplitFileResponseMessage::release_split_file_content_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
  
  return split_file_content__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RetrieveSplitFileResponseMessage::set_allocated_split_file_content_(::std::string* split_file_content_) {
  if (split_file_content_ != NULL) {
    
  } else {
    
  }
  split_file_content__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), split_file_content_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.RetrieveSplitFileResponseMessage.split_file_content_)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RetrieveSplitFileMessage_2eproto__INCLUDED
