// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartReduceMessage.proto

#ifndef PROTOBUF_StartReduceMessage_2eproto__INCLUDED
#define PROTOBUF_StartReduceMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "InternalType.pb.h"
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_StartReduceMessage_2eproto();
void protobuf_AssignDesc_StartReduceMessage_2eproto();
void protobuf_ShutdownFile_StartReduceMessage_2eproto();

class StartReduceRequestMessage;
class StartReduceResponseMessage;

// ===================================================================

class StartReduceRequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.StartReduceRequestMessage) */ {
 public:
  StartReduceRequestMessage();
  virtual ~StartReduceRequestMessage();

  StartReduceRequestMessage(const StartReduceRequestMessage& from);

  inline StartReduceRequestMessage& operator=(const StartReduceRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartReduceRequestMessage& default_instance();

  void Swap(StartReduceRequestMessage* other);

  // implements Message ----------------------------------------------

  inline StartReduceRequestMessage* New() const { return New(NULL); }

  StartReduceRequestMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartReduceRequestMessage& from);
  void MergeFrom(const StartReduceRequestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StartReduceRequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional string listen_ip_ = 3;
  void clear_listen_ip_();
  static const int kListenIpFieldNumber = 3;
  const ::std::string& listen_ip_() const;
  void set_listen_ip_(const ::std::string& value);
  void set_listen_ip_(const char* value);
  void set_listen_ip_(const char* value, size_t size);
  ::std::string* mutable_listen_ip_();
  ::std::string* release_listen_ip_();
  void set_allocated_listen_ip_(::std::string* listen_ip_);

  // optional string listen_port_ = 4;
  void clear_listen_port_();
  static const int kListenPortFieldNumber = 4;
  const ::std::string& listen_port_() const;
  void set_listen_port_(const ::std::string& value);
  void set_listen_port_(const char* value);
  void set_listen_port_(const char* value, size_t size);
  ::std::string* mutable_listen_port_();
  ::std::string* release_listen_port_();
  void set_allocated_listen_port_(::std::string* listen_port_);

  // repeated string file_list_ = 5;
  int file_list__size() const;
  void clear_file_list_();
  static const int kFileListFieldNumber = 5;
  const ::std::string& file_list_(int index) const;
  ::std::string* mutable_file_list_(int index);
  void set_file_list_(int index, const ::std::string& value);
  void set_file_list_(int index, const char* value);
  void set_file_list_(int index, const char* value, size_t size);
  ::std::string* add_file_list_();
  void add_file_list_(const ::std::string& value);
  void add_file_list_(const char* value);
  void add_file_list_(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& file_list_() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_file_list_();

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.StartReduceRequestMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  ::google::protobuf::internal::ArenaStringPtr listen_ip__;
  ::google::protobuf::internal::ArenaStringPtr listen_port__;
  ::google::protobuf::RepeatedPtrField< ::std::string> file_list__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_StartReduceMessage_2eproto();
  friend void protobuf_AssignDesc_StartReduceMessage_2eproto();
  friend void protobuf_ShutdownFile_StartReduceMessage_2eproto();

  void InitAsDefaultInstance();
  static StartReduceRequestMessage* default_instance_;
};
// -------------------------------------------------------------------

class StartReduceResponseMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Imagine_MapReduce.Internal.StartReduceResponseMessage) */ {
 public:
  StartReduceResponseMessage();
  virtual ~StartReduceResponseMessage();

  StartReduceResponseMessage(const StartReduceResponseMessage& from);

  inline StartReduceResponseMessage& operator=(const StartReduceResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartReduceResponseMessage& default_instance();

  void Swap(StartReduceResponseMessage* other);

  // implements Message ----------------------------------------------

  inline StartReduceResponseMessage* New() const { return New(NULL); }

  StartReduceResponseMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartReduceResponseMessage& from);
  void MergeFrom(const StartReduceResponseMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StartReduceResponseMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  void clear_send_identity_();
  static const int kSendIdentityFieldNumber = 1;
  ::Imagine_MapReduce::Internal::Identity send_identity_() const;
  void set_send_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  void clear_recv_identity_();
  static const int kRecvIdentityFieldNumber = 2;
  ::Imagine_MapReduce::Internal::Identity recv_identity_() const;
  void set_recv_identity_(::Imagine_MapReduce::Internal::Identity value);

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  void clear_status_();
  static const int kStatusFieldNumber = 3;
  ::Imagine_MapReduce::Internal::Status status_() const;
  void set_status_(::Imagine_MapReduce::Internal::Status value);

  // @@protoc_insertion_point(class_scope:Imagine_MapReduce.Internal.StartReduceResponseMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int send_identity__;
  int recv_identity__;
  int status__;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_StartReduceMessage_2eproto();
  friend void protobuf_AssignDesc_StartReduceMessage_2eproto();
  friend void protobuf_ShutdownFile_StartReduceMessage_2eproto();

  void InitAsDefaultInstance();
  static StartReduceResponseMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StartReduceRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void StartReduceRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity StartReduceRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void StartReduceRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void StartReduceRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity StartReduceRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void StartReduceRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.recv_identity_)
}

// optional string listen_ip_ = 3;
inline void StartReduceRequestMessage::clear_listen_ip_() {
  listen_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StartReduceRequestMessage::listen_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  return listen_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartReduceRequestMessage::set_listen_ip_(const ::std::string& value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
inline void StartReduceRequestMessage::set_listen_ip_(const char* value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
inline void StartReduceRequestMessage::set_listen_ip_(const char* value, size_t size) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
inline ::std::string* StartReduceRequestMessage::mutable_listen_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  return listen_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StartReduceRequestMessage::release_listen_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  
  return listen_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartReduceRequestMessage::set_allocated_listen_ip_(::std::string* listen_ip_) {
  if (listen_ip_ != NULL) {
    
  } else {
    
  }
  listen_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}

// optional string listen_port_ = 4;
inline void StartReduceRequestMessage::clear_listen_port_() {
  listen_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StartReduceRequestMessage::listen_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  return listen_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartReduceRequestMessage::set_listen_port_(const ::std::string& value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
inline void StartReduceRequestMessage::set_listen_port_(const char* value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
inline void StartReduceRequestMessage::set_listen_port_(const char* value, size_t size) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
inline ::std::string* StartReduceRequestMessage::mutable_listen_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  return listen_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StartReduceRequestMessage::release_listen_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  
  return listen_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StartReduceRequestMessage::set_allocated_listen_port_(::std::string* listen_port_) {
  if (listen_port_ != NULL) {
    
  } else {
    
  }
  listen_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}

// repeated string file_list_ = 5;
inline int StartReduceRequestMessage::file_list__size() const {
  return file_list__.size();
}
inline void StartReduceRequestMessage::clear_file_list_() {
  file_list__.Clear();
}
inline const ::std::string& StartReduceRequestMessage::file_list_(int index) const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Get(index);
}
inline ::std::string* StartReduceRequestMessage::mutable_file_list_(int index) {
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Mutable(index);
}
inline void StartReduceRequestMessage::set_file_list_(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  file_list__.Mutable(index)->assign(value);
}
inline void StartReduceRequestMessage::set_file_list_(int index, const char* value) {
  file_list__.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
inline void StartReduceRequestMessage::set_file_list_(int index, const char* value, size_t size) {
  file_list__.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
inline ::std::string* StartReduceRequestMessage::add_file_list_() {
  // @@protoc_insertion_point(field_add_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Add();
}
inline void StartReduceRequestMessage::add_file_list_(const ::std::string& value) {
  file_list__.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
inline void StartReduceRequestMessage::add_file_list_(const char* value) {
  file_list__.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
inline void StartReduceRequestMessage::add_file_list_(const char* value, size_t size) {
  file_list__.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
StartReduceRequestMessage::file_list_() const {
  // @@protoc_insertion_point(field_list:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
StartReduceRequestMessage::mutable_file_list_() {
  // @@protoc_insertion_point(field_mutable_list:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return &file_list__;
}

// -------------------------------------------------------------------

// StartReduceResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
inline void StartReduceResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity StartReduceResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
inline void StartReduceResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
inline void StartReduceResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
inline ::Imagine_MapReduce::Internal::Identity StartReduceResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
inline void StartReduceResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
inline void StartReduceResponseMessage::clear_status_() {
  status__ = 0;
}
inline ::Imagine_MapReduce::Internal::Status StartReduceResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
inline void StartReduceResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.status_)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StartReduceMessage_2eproto__INCLUDED
