// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Imagine_MapReduce/InternalType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

namespace {

const ::google::protobuf::EnumDescriptor* Identity_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* TaskStatus_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* Status_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_InternalType_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_InternalType_2eproto() {
  protobuf_AddDesc_InternalType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "InternalType.proto");
  GOOGLE_CHECK(file != NULL);
  Identity_descriptor_ = file->enum_type(0);
  TaskStatus_descriptor_ = file->enum_type(1);
  Status_descriptor_ = file->enum_type(2);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_InternalType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_InternalType_2eproto() {
}

void protobuf_AddDesc_InternalType_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_InternalType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022InternalType.proto\022\032Imagine_MapReduce."
    "Internal*/\n\010Identity\022\n\n\006Mapper\020\000\022\013\n\007Redu"
    "cer\020\001\022\n\n\006Master\020\002*0\n\nTaskStatus\022\t\n\005Start"
    "\020\000\022\013\n\007Process\020\001\022\n\n\006Finish\020\002*\033\n\006Status\022\006\n"
    "\002Ok\020\000\022\t\n\005Error\020\001b\006proto3", 184);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InternalType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_InternalType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_InternalType_2eproto {
  StaticDescriptorInitializer_InternalType_2eproto() {
    protobuf_AddDesc_InternalType_2eproto();
  }
} static_descriptor_initializer_InternalType_2eproto_;
const ::google::protobuf::EnumDescriptor* Identity_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Identity_descriptor_;
}
bool Identity_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* TaskStatus_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TaskStatus_descriptor_;
}
bool TaskStatus_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Status_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Status_descriptor_;
}
bool Status_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)
