// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapTaskMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Imagine_MapReduce/MapTaskMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

namespace {

const ::google::protobuf::Descriptor* MapTaskRequestMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MapTaskRequestMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* MapTaskResponseMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MapTaskResponseMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MapTaskMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_MapTaskMessage_2eproto() {
  protobuf_AddDesc_MapTaskMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MapTaskMessage.proto");
  GOOGLE_CHECK(file != NULL);
  MapTaskRequestMessage_descriptor_ = file->message_type(0);
  static const int MapTaskRequestMessage_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, file_name__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, split_size__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, listen_ip__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, listen_port__),
  };
  MapTaskRequestMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MapTaskRequestMessage_descriptor_,
      MapTaskRequestMessage::default_instance_,
      MapTaskRequestMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(MapTaskRequestMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskRequestMessage, _is_default_instance_));
  MapTaskResponseMessage_descriptor_ = file->message_type(1);
  static const int MapTaskResponseMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskResponseMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskResponseMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskResponseMessage, status__),
  };
  MapTaskResponseMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MapTaskResponseMessage_descriptor_,
      MapTaskResponseMessage::default_instance_,
      MapTaskResponseMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(MapTaskResponseMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskResponseMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapTaskResponseMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MapTaskMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MapTaskRequestMessage_descriptor_, &MapTaskRequestMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MapTaskResponseMessage_descriptor_, &MapTaskResponseMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MapTaskMessage_2eproto() {
  delete MapTaskRequestMessage::default_instance_;
  delete MapTaskRequestMessage_reflection_;
  delete MapTaskResponseMessage::default_instance_;
  delete MapTaskResponseMessage_reflection_;
}

void protobuf_AddDesc_MapTaskMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_MapTaskMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Imagine_MapReduce::Internal::protobuf_AddDesc_InternalType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024MapTaskMessage.proto\022\032Imagine_MapReduc"
    "e.Internal\032\022InternalType.proto\"\346\001\n\025MapTa"
    "skRequestMessage\022<\n\016send_identity_\030\001 \001(\016"
    "2$.Imagine_MapReduce.Internal.Identity\022<"
    "\n\016recv_identity_\030\002 \001(\0162$.Imagine_MapRedu"
    "ce.Internal.Identity\022\022\n\nfile_name_\030\003 \001(\t"
    "\022\023\n\013split_size_\030\004 \001(\r\022\022\n\nlisten_ip_\030\005 \001("
    "\t\022\024\n\014listen_port_\030\006 \001(\t\"\311\001\n\026MapTaskRespo"
    "nseMessage\022<\n\016send_identity_\030\001 \001(\0162$.Ima"
    "gine_MapReduce.Internal.Identity\022<\n\016recv"
    "_identity_\030\002 \001(\0162$.Imagine_MapReduce.Int"
    "ernal.Identity\0223\n\007status_\030\003 \001(\0162\".Imagin"
    "e_MapReduce.Internal.Statusb\006proto3", 515);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MapTaskMessage.proto", &protobuf_RegisterTypes);
  MapTaskRequestMessage::default_instance_ = new MapTaskRequestMessage();
  MapTaskResponseMessage::default_instance_ = new MapTaskResponseMessage();
  MapTaskRequestMessage::default_instance_->InitAsDefaultInstance();
  MapTaskResponseMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MapTaskMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MapTaskMessage_2eproto {
  StaticDescriptorInitializer_MapTaskMessage_2eproto() {
    protobuf_AddDesc_MapTaskMessage_2eproto();
  }
} static_descriptor_initializer_MapTaskMessage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapTaskRequestMessage::kSendIdentityFieldNumber;
const int MapTaskRequestMessage::kRecvIdentityFieldNumber;
const int MapTaskRequestMessage::kFileNameFieldNumber;
const int MapTaskRequestMessage::kSplitSizeFieldNumber;
const int MapTaskRequestMessage::kListenIpFieldNumber;
const int MapTaskRequestMessage::kListenPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapTaskRequestMessage::MapTaskRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.MapTaskRequestMessage)
}

void MapTaskRequestMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MapTaskRequestMessage::MapTaskRequestMessage(const MapTaskRequestMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.MapTaskRequestMessage)
}

void MapTaskRequestMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  file_name__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_size__ = 0u;
  listen_ip__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MapTaskRequestMessage::~MapTaskRequestMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  SharedDtor();
}

void MapTaskRequestMessage::SharedDtor() {
  file_name__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_ip__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MapTaskRequestMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MapTaskRequestMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MapTaskRequestMessage_descriptor_;
}

const MapTaskRequestMessage& MapTaskRequestMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MapTaskMessage_2eproto();
  return *default_instance_;
}

MapTaskRequestMessage* MapTaskRequestMessage::default_instance_ = NULL;

MapTaskRequestMessage* MapTaskRequestMessage::New(::google::protobuf::Arena* arena) const {
  MapTaskRequestMessage* n = new MapTaskRequestMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MapTaskRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MapTaskRequestMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MapTaskRequestMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, recv_identity__);
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_size__ = 0u;
  listen_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool MapTaskRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_file_name_;
        break;
      }

      // optional string file_name_ = 3;
      case 3: {
        if (tag == 26) {
         parse_file_name_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_name_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file_name_().data(), this->file_name_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_split_size_;
        break;
      }

      // optional uint32 split_size_ = 4;
      case 4: {
        if (tag == 32) {
         parse_split_size_:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &split_size__)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_listen_ip_;
        break;
      }

      // optional string listen_ip_ = 5;
      case 5: {
        if (tag == 42) {
         parse_listen_ip_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_listen_ip_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->listen_ip_().data(), this->listen_ip_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_listen_port_;
        break;
      }

      // optional string listen_port_ = 6;
      case 6: {
        if (tag == 50) {
         parse_listen_port_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_listen_port_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->listen_port_().data(), this->listen_port_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  return false;
#undef DO_
}

void MapTaskRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_name_().data(), this->file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->file_name_(), output);
  }

  // optional uint32 split_size_ = 4;
  if (this->split_size_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->split_size_(), output);
  }

  // optional string listen_ip_ = 5;
  if (this->listen_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_ip_().data(), this->listen_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->listen_ip_(), output);
  }

  // optional string listen_port_ = 6;
  if (this->listen_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_port_().data(), this->listen_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->listen_port_(), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.MapTaskRequestMessage)
}

::google::protobuf::uint8* MapTaskRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_name_().data(), this->file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->file_name_(), target);
  }

  // optional uint32 split_size_ = 4;
  if (this->split_size_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->split_size_(), target);
  }

  // optional string listen_ip_ = 5;
  if (this->listen_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_ip_().data(), this->listen_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->listen_ip_(), target);
  }

  // optional string listen_port_ = 6;
  if (this->listen_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_port_().data(), this->listen_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->listen_port_(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  return target;
}

int MapTaskRequestMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file_name_());
  }

  // optional uint32 split_size_ = 4;
  if (this->split_size_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->split_size_());
  }

  // optional string listen_ip_ = 5;
  if (this->listen_ip_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->listen_ip_());
  }

  // optional string listen_port_ = 6;
  if (this->listen_port_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->listen_port_());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MapTaskRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MapTaskRequestMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MapTaskRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.MapTaskRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.MapTaskRequestMessage)
    MergeFrom(*source);
  }
}

void MapTaskRequestMessage::MergeFrom(const MapTaskRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.file_name_().size() > 0) {

    file_name__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_name__);
  }
  if (from.split_size_() != 0) {
    set_split_size_(from.split_size_());
  }
  if (from.listen_ip_().size() > 0) {

    listen_ip__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.listen_ip__);
  }
  if (from.listen_port_().size() > 0) {

    listen_port__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.listen_port__);
  }
}

void MapTaskRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapTaskRequestMessage::CopyFrom(const MapTaskRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.MapTaskRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapTaskRequestMessage::IsInitialized() const {

  return true;
}

void MapTaskRequestMessage::Swap(MapTaskRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapTaskRequestMessage::InternalSwap(MapTaskRequestMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  file_name__.Swap(&other->file_name__);
  std::swap(split_size__, other->split_size__);
  listen_ip__.Swap(&other->listen_ip__);
  listen_port__.Swap(&other->listen_port__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MapTaskRequestMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MapTaskRequestMessage_descriptor_;
  metadata.reflection = MapTaskRequestMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MapTaskRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void MapTaskRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity MapTaskRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void MapTaskRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void MapTaskRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity MapTaskRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void MapTaskRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.recv_identity_)
}

// optional string file_name_ = 3;
void MapTaskRequestMessage::clear_file_name_() {
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MapTaskRequestMessage::file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
  return file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_file_name_(const ::std::string& value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
}
 void MapTaskRequestMessage::set_file_name_(const char* value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
}
 void MapTaskRequestMessage::set_file_name_(const char* value, size_t size) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
}
 ::std::string* MapTaskRequestMessage::mutable_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
  return file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MapTaskRequestMessage::release_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
  
  return file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_allocated_file_name_(::std::string* file_name_) {
  if (file_name_ != NULL) {
    
  } else {
    
  }
  file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.MapTaskRequestMessage.file_name_)
}

// optional uint32 split_size_ = 4;
void MapTaskRequestMessage::clear_split_size_() {
  split_size__ = 0u;
}
 ::google::protobuf::uint32 MapTaskRequestMessage::split_size_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.split_size_)
  return split_size__;
}
 void MapTaskRequestMessage::set_split_size_(::google::protobuf::uint32 value) {
  
  split_size__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.split_size_)
}

// optional string listen_ip_ = 5;
void MapTaskRequestMessage::clear_listen_ip_() {
  listen_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MapTaskRequestMessage::listen_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
  return listen_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_listen_ip_(const ::std::string& value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
}
 void MapTaskRequestMessage::set_listen_ip_(const char* value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
}
 void MapTaskRequestMessage::set_listen_ip_(const char* value, size_t size) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
}
 ::std::string* MapTaskRequestMessage::mutable_listen_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
  return listen_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MapTaskRequestMessage::release_listen_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
  
  return listen_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_allocated_listen_ip_(::std::string* listen_ip_) {
  if (listen_ip_ != NULL) {
    
  } else {
    
  }
  listen_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_ip_)
}

// optional string listen_port_ = 6;
void MapTaskRequestMessage::clear_listen_port_() {
  listen_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MapTaskRequestMessage::listen_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
  return listen_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_listen_port_(const ::std::string& value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
}
 void MapTaskRequestMessage::set_listen_port_(const char* value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
}
 void MapTaskRequestMessage::set_listen_port_(const char* value, size_t size) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
}
 ::std::string* MapTaskRequestMessage::mutable_listen_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
  return listen_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MapTaskRequestMessage::release_listen_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
  
  return listen_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MapTaskRequestMessage::set_allocated_listen_port_(::std::string* listen_port_) {
  if (listen_port_ != NULL) {
    
  } else {
    
  }
  listen_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.MapTaskRequestMessage.listen_port_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapTaskResponseMessage::kSendIdentityFieldNumber;
const int MapTaskResponseMessage::kRecvIdentityFieldNumber;
const int MapTaskResponseMessage::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapTaskResponseMessage::MapTaskResponseMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.MapTaskResponseMessage)
}

void MapTaskResponseMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MapTaskResponseMessage::MapTaskResponseMessage(const MapTaskResponseMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.MapTaskResponseMessage)
}

void MapTaskResponseMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  status__ = 0;
}

MapTaskResponseMessage::~MapTaskResponseMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  SharedDtor();
}

void MapTaskResponseMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MapTaskResponseMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MapTaskResponseMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MapTaskResponseMessage_descriptor_;
}

const MapTaskResponseMessage& MapTaskResponseMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MapTaskMessage_2eproto();
  return *default_instance_;
}

MapTaskResponseMessage* MapTaskResponseMessage::default_instance_ = NULL;

MapTaskResponseMessage* MapTaskResponseMessage::New(::google::protobuf::Arena* arena) const {
  MapTaskResponseMessage* n = new MapTaskResponseMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MapTaskResponseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MapTaskResponseMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MapTaskResponseMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, status__);

#undef ZR_HELPER_
#undef ZR_

}

bool MapTaskResponseMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_status_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Status status_ = 3;
      case 3: {
        if (tag == 24) {
         parse_status_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status_(static_cast< ::Imagine_MapReduce::Internal::Status >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  return false;
#undef DO_
}

void MapTaskResponseMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->status_(), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.MapTaskResponseMessage)
}

::google::protobuf::uint8* MapTaskResponseMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->status_(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  return target;
}

int MapTaskResponseMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status_());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MapTaskResponseMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MapTaskResponseMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MapTaskResponseMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.MapTaskResponseMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.MapTaskResponseMessage)
    MergeFrom(*source);
  }
}

void MapTaskResponseMessage::MergeFrom(const MapTaskResponseMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.status_() != 0) {
    set_status_(from.status_());
  }
}

void MapTaskResponseMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapTaskResponseMessage::CopyFrom(const MapTaskResponseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.MapTaskResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapTaskResponseMessage::IsInitialized() const {

  return true;
}

void MapTaskResponseMessage::Swap(MapTaskResponseMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapTaskResponseMessage::InternalSwap(MapTaskResponseMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  std::swap(status__, other->status__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MapTaskResponseMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MapTaskResponseMessage_descriptor_;
  metadata.reflection = MapTaskResponseMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MapTaskResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void MapTaskResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity MapTaskResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void MapTaskResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void MapTaskResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity MapTaskResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void MapTaskResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
void MapTaskResponseMessage::clear_status_() {
  status__ = 0;
}
 ::Imagine_MapReduce::Internal::Status MapTaskResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.MapTaskResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
 void MapTaskResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.MapTaskResponseMessage.status_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)
