// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReduceTaskMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Imagine_MapReduce/ReduceTaskMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

namespace {

const ::google::protobuf::Descriptor* ReduceTaskRequestMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReduceTaskRequestMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReduceTaskResponseMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReduceTaskResponseMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ReduceTaskMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_ReduceTaskMessage_2eproto() {
  protobuf_AddDesc_ReduceTaskMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ReduceTaskMessage.proto");
  GOOGLE_CHECK(file != NULL);
  ReduceTaskRequestMessage_descriptor_ = file->message_type(0);
  static const int ReduceTaskRequestMessage_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, file_name__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, split_file_name__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, split_num__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, mapper_ip__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, mapper_port__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, master_ip__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, master_port__),
  };
  ReduceTaskRequestMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReduceTaskRequestMessage_descriptor_,
      ReduceTaskRequestMessage::default_instance_,
      ReduceTaskRequestMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReduceTaskRequestMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskRequestMessage, _is_default_instance_));
  ReduceTaskResponseMessage_descriptor_ = file->message_type(1);
  static const int ReduceTaskResponseMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskResponseMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskResponseMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskResponseMessage, status__),
  };
  ReduceTaskResponseMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReduceTaskResponseMessage_descriptor_,
      ReduceTaskResponseMessage::default_instance_,
      ReduceTaskResponseMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReduceTaskResponseMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskResponseMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReduceTaskResponseMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ReduceTaskMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReduceTaskRequestMessage_descriptor_, &ReduceTaskRequestMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReduceTaskResponseMessage_descriptor_, &ReduceTaskResponseMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ReduceTaskMessage_2eproto() {
  delete ReduceTaskRequestMessage::default_instance_;
  delete ReduceTaskRequestMessage_reflection_;
  delete ReduceTaskResponseMessage::default_instance_;
  delete ReduceTaskResponseMessage_reflection_;
}

void protobuf_AddDesc_ReduceTaskMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ReduceTaskMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Imagine_MapReduce::Internal::protobuf_AddDesc_InternalType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027ReduceTaskMessage.proto\022\032Imagine_MapRe"
    "duce.Internal\032\022InternalType.proto\"\254\002\n\030Re"
    "duceTaskRequestMessage\022<\n\016send_identity_"
    "\030\001 \001(\0162$.Imagine_MapReduce.Internal.Iden"
    "tity\022<\n\016recv_identity_\030\002 \001(\0162$.Imagine_M"
    "apReduce.Internal.Identity\022\022\n\nfile_name_"
    "\030\003 \001(\t\022\030\n\020split_file_name_\030\004 \001(\t\022\022\n\nspli"
    "t_num_\030\005 \001(\r\022\022\n\nmapper_ip_\030\006 \001(\t\022\024\n\014mapp"
    "er_port_\030\007 \001(\t\022\022\n\nmaster_ip_\030\010 \001(\t\022\024\n\014ma"
    "ster_port_\030\t \001(\t\"\314\001\n\031ReduceTaskResponseM"
    "essage\022<\n\016send_identity_\030\001 \001(\0162$.Imagine"
    "_MapReduce.Internal.Identity\022<\n\016recv_ide"
    "ntity_\030\002 \001(\0162$.Imagine_MapReduce.Interna"
    "l.Identity\0223\n\007status_\030\003 \001(\0162\".Imagine_Ma"
    "pReduce.Internal.Statusb\006proto3", 591);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ReduceTaskMessage.proto", &protobuf_RegisterTypes);
  ReduceTaskRequestMessage::default_instance_ = new ReduceTaskRequestMessage();
  ReduceTaskResponseMessage::default_instance_ = new ReduceTaskResponseMessage();
  ReduceTaskRequestMessage::default_instance_->InitAsDefaultInstance();
  ReduceTaskResponseMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ReduceTaskMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ReduceTaskMessage_2eproto {
  StaticDescriptorInitializer_ReduceTaskMessage_2eproto() {
    protobuf_AddDesc_ReduceTaskMessage_2eproto();
  }
} static_descriptor_initializer_ReduceTaskMessage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReduceTaskRequestMessage::kSendIdentityFieldNumber;
const int ReduceTaskRequestMessage::kRecvIdentityFieldNumber;
const int ReduceTaskRequestMessage::kFileNameFieldNumber;
const int ReduceTaskRequestMessage::kSplitFileNameFieldNumber;
const int ReduceTaskRequestMessage::kSplitNumFieldNumber;
const int ReduceTaskRequestMessage::kMapperIpFieldNumber;
const int ReduceTaskRequestMessage::kMapperPortFieldNumber;
const int ReduceTaskRequestMessage::kMasterIpFieldNumber;
const int ReduceTaskRequestMessage::kMasterPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReduceTaskRequestMessage::ReduceTaskRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
}

void ReduceTaskRequestMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReduceTaskRequestMessage::ReduceTaskRequestMessage(const ReduceTaskRequestMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
}

void ReduceTaskRequestMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  file_name__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_file_name__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_num__ = 0u;
  mapper_ip__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mapper_port__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_ip__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_port__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReduceTaskRequestMessage::~ReduceTaskRequestMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  SharedDtor();
}

void ReduceTaskRequestMessage::SharedDtor() {
  file_name__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_file_name__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mapper_ip__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mapper_port__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_ip__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_port__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ReduceTaskRequestMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReduceTaskRequestMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReduceTaskRequestMessage_descriptor_;
}

const ReduceTaskRequestMessage& ReduceTaskRequestMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ReduceTaskMessage_2eproto();
  return *default_instance_;
}

ReduceTaskRequestMessage* ReduceTaskRequestMessage::default_instance_ = NULL;

ReduceTaskRequestMessage* ReduceTaskRequestMessage::New(::google::protobuf::Arena* arena) const {
  ReduceTaskRequestMessage* n = new ReduceTaskRequestMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReduceTaskRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ReduceTaskRequestMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ReduceTaskRequestMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, recv_identity__);
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  split_num__ = 0u;
  mapper_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mapper_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool ReduceTaskRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_file_name_;
        break;
      }

      // optional string file_name_ = 3;
      case 3: {
        if (tag == 26) {
         parse_file_name_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_name_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file_name_().data(), this->file_name_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_split_file_name_;
        break;
      }

      // optional string split_file_name_ = 4;
      case 4: {
        if (tag == 34) {
         parse_split_file_name_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_split_file_name_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->split_file_name_().data(), this->split_file_name_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_split_num_;
        break;
      }

      // optional uint32 split_num_ = 5;
      case 5: {
        if (tag == 40) {
         parse_split_num_:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &split_num__)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_mapper_ip_;
        break;
      }

      // optional string mapper_ip_ = 6;
      case 6: {
        if (tag == 50) {
         parse_mapper_ip_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mapper_ip_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mapper_ip_().data(), this->mapper_ip_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_mapper_port_;
        break;
      }

      // optional string mapper_port_ = 7;
      case 7: {
        if (tag == 58) {
         parse_mapper_port_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mapper_port_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mapper_port_().data(), this->mapper_port_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_master_ip_;
        break;
      }

      // optional string master_ip_ = 8;
      case 8: {
        if (tag == 66) {
         parse_master_ip_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_master_ip_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->master_ip_().data(), this->master_ip_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_master_port_;
        break;
      }

      // optional string master_port_ = 9;
      case 9: {
        if (tag == 74) {
         parse_master_port_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_master_port_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->master_port_().data(), this->master_port_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  return false;
#undef DO_
}

void ReduceTaskRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_name_().data(), this->file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->file_name_(), output);
  }

  // optional string split_file_name_ = 4;
  if (this->split_file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->split_file_name_().data(), this->split_file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->split_file_name_(), output);
  }

  // optional uint32 split_num_ = 5;
  if (this->split_num_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->split_num_(), output);
  }

  // optional string mapper_ip_ = 6;
  if (this->mapper_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mapper_ip_().data(), this->mapper_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->mapper_ip_(), output);
  }

  // optional string mapper_port_ = 7;
  if (this->mapper_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mapper_port_().data(), this->mapper_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->mapper_port_(), output);
  }

  // optional string master_ip_ = 8;
  if (this->master_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_ip_().data(), this->master_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->master_ip_(), output);
  }

  // optional string master_port_ = 9;
  if (this->master_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_port_().data(), this->master_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->master_port_(), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
}

::google::protobuf::uint8* ReduceTaskRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_name_().data(), this->file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->file_name_(), target);
  }

  // optional string split_file_name_ = 4;
  if (this->split_file_name_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->split_file_name_().data(), this->split_file_name_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->split_file_name_(), target);
  }

  // optional uint32 split_num_ = 5;
  if (this->split_num_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->split_num_(), target);
  }

  // optional string mapper_ip_ = 6;
  if (this->mapper_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mapper_ip_().data(), this->mapper_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->mapper_ip_(), target);
  }

  // optional string mapper_port_ = 7;
  if (this->mapper_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mapper_port_().data(), this->mapper_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->mapper_port_(), target);
  }

  // optional string master_ip_ = 8;
  if (this->master_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_ip_().data(), this->master_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->master_ip_(), target);
  }

  // optional string master_port_ = 9;
  if (this->master_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_port_().data(), this->master_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->master_port_(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  return target;
}

int ReduceTaskRequestMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional string file_name_ = 3;
  if (this->file_name_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file_name_());
  }

  // optional string split_file_name_ = 4;
  if (this->split_file_name_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->split_file_name_());
  }

  // optional uint32 split_num_ = 5;
  if (this->split_num_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->split_num_());
  }

  // optional string mapper_ip_ = 6;
  if (this->mapper_ip_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mapper_ip_());
  }

  // optional string mapper_port_ = 7;
  if (this->mapper_port_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mapper_port_());
  }

  // optional string master_ip_ = 8;
  if (this->master_ip_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->master_ip_());
  }

  // optional string master_port_ = 9;
  if (this->master_port_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->master_port_());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReduceTaskRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReduceTaskRequestMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReduceTaskRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
    MergeFrom(*source);
  }
}

void ReduceTaskRequestMessage::MergeFrom(const ReduceTaskRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.file_name_().size() > 0) {

    file_name__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_name__);
  }
  if (from.split_file_name_().size() > 0) {

    split_file_name__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.split_file_name__);
  }
  if (from.split_num_() != 0) {
    set_split_num_(from.split_num_());
  }
  if (from.mapper_ip_().size() > 0) {

    mapper_ip__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mapper_ip__);
  }
  if (from.mapper_port_().size() > 0) {

    mapper_port__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mapper_port__);
  }
  if (from.master_ip_().size() > 0) {

    master_ip__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_ip__);
  }
  if (from.master_port_().size() > 0) {

    master_port__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_port__);
  }
}

void ReduceTaskRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceTaskRequestMessage::CopyFrom(const ReduceTaskRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.ReduceTaskRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceTaskRequestMessage::IsInitialized() const {

  return true;
}

void ReduceTaskRequestMessage::Swap(ReduceTaskRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReduceTaskRequestMessage::InternalSwap(ReduceTaskRequestMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  file_name__.Swap(&other->file_name__);
  split_file_name__.Swap(&other->split_file_name__);
  std::swap(split_num__, other->split_num__);
  mapper_ip__.Swap(&other->mapper_ip__);
  mapper_port__.Swap(&other->mapper_port__);
  master_ip__.Swap(&other->master_ip__);
  master_port__.Swap(&other->master_port__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReduceTaskRequestMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReduceTaskRequestMessage_descriptor_;
  metadata.reflection = ReduceTaskRequestMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReduceTaskRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void ReduceTaskRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity ReduceTaskRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void ReduceTaskRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void ReduceTaskRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity ReduceTaskRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void ReduceTaskRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.recv_identity_)
}

// optional string file_name_ = 3;
void ReduceTaskRequestMessage::clear_file_name_() {
  file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  return file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_file_name_(const ::std::string& value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
 void ReduceTaskRequestMessage::set_file_name_(const char* value) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
 void ReduceTaskRequestMessage::set_file_name_(const char* value, size_t size) {
  
  file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  return file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
  
  return file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_file_name_(::std::string* file_name_) {
  if (file_name_ != NULL) {
    
  } else {
    
  }
  file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.file_name_)
}

// optional string split_file_name_ = 4;
void ReduceTaskRequestMessage::clear_split_file_name_() {
  split_file_name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::split_file_name_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  return split_file_name__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_split_file_name_(const ::std::string& value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
 void ReduceTaskRequestMessage::set_split_file_name_(const char* value) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
 void ReduceTaskRequestMessage::set_split_file_name_(const char* value, size_t size) {
  
  split_file_name__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_split_file_name_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  return split_file_name__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_split_file_name_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
  
  return split_file_name__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_split_file_name_(::std::string* split_file_name_) {
  if (split_file_name_ != NULL) {
    
  } else {
    
  }
  split_file_name__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), split_file_name_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_file_name_)
}

// optional uint32 split_num_ = 5;
void ReduceTaskRequestMessage::clear_split_num_() {
  split_num__ = 0u;
}
 ::google::protobuf::uint32 ReduceTaskRequestMessage::split_num_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_num_)
  return split_num__;
}
 void ReduceTaskRequestMessage::set_split_num_(::google::protobuf::uint32 value) {
  
  split_num__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.split_num_)
}

// optional string mapper_ip_ = 6;
void ReduceTaskRequestMessage::clear_mapper_ip_() {
  mapper_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::mapper_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  return mapper_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_mapper_ip_(const ::std::string& value) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
 void ReduceTaskRequestMessage::set_mapper_ip_(const char* value) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
 void ReduceTaskRequestMessage::set_mapper_ip_(const char* value, size_t size) {
  
  mapper_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_mapper_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  return mapper_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_mapper_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
  
  return mapper_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_mapper_ip_(::std::string* mapper_ip_) {
  if (mapper_ip_ != NULL) {
    
  } else {
    
  }
  mapper_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapper_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_ip_)
}

// optional string mapper_port_ = 7;
void ReduceTaskRequestMessage::clear_mapper_port_() {
  mapper_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::mapper_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  return mapper_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_mapper_port_(const ::std::string& value) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
 void ReduceTaskRequestMessage::set_mapper_port_(const char* value) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
 void ReduceTaskRequestMessage::set_mapper_port_(const char* value, size_t size) {
  
  mapper_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_mapper_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  return mapper_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_mapper_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
  
  return mapper_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_mapper_port_(::std::string* mapper_port_) {
  if (mapper_port_ != NULL) {
    
  } else {
    
  }
  mapper_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapper_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.mapper_port_)
}

// optional string master_ip_ = 8;
void ReduceTaskRequestMessage::clear_master_ip_() {
  master_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::master_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  return master_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_master_ip_(const ::std::string& value) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
 void ReduceTaskRequestMessage::set_master_ip_(const char* value) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
 void ReduceTaskRequestMessage::set_master_ip_(const char* value, size_t size) {
  
  master_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_master_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  return master_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_master_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
  
  return master_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_master_ip_(::std::string* master_ip_) {
  if (master_ip_ != NULL) {
    
  } else {
    
  }
  master_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), master_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_ip_)
}

// optional string master_port_ = 9;
void ReduceTaskRequestMessage::clear_master_port_() {
  master_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ReduceTaskRequestMessage::master_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  return master_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_master_port_(const ::std::string& value) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
 void ReduceTaskRequestMessage::set_master_port_(const char* value) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
 void ReduceTaskRequestMessage::set_master_port_(const char* value, size_t size) {
  
  master_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}
 ::std::string* ReduceTaskRequestMessage::mutable_master_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  return master_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ReduceTaskRequestMessage::release_master_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
  
  return master_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ReduceTaskRequestMessage::set_allocated_master_port_(::std::string* master_port_) {
  if (master_port_ != NULL) {
    
  } else {
    
  }
  master_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), master_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.ReduceTaskRequestMessage.master_port_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReduceTaskResponseMessage::kSendIdentityFieldNumber;
const int ReduceTaskResponseMessage::kRecvIdentityFieldNumber;
const int ReduceTaskResponseMessage::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReduceTaskResponseMessage::ReduceTaskResponseMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
}

void ReduceTaskResponseMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReduceTaskResponseMessage::ReduceTaskResponseMessage(const ReduceTaskResponseMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
}

void ReduceTaskResponseMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  status__ = 0;
}

ReduceTaskResponseMessage::~ReduceTaskResponseMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  SharedDtor();
}

void ReduceTaskResponseMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReduceTaskResponseMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReduceTaskResponseMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReduceTaskResponseMessage_descriptor_;
}

const ReduceTaskResponseMessage& ReduceTaskResponseMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ReduceTaskMessage_2eproto();
  return *default_instance_;
}

ReduceTaskResponseMessage* ReduceTaskResponseMessage::default_instance_ = NULL;

ReduceTaskResponseMessage* ReduceTaskResponseMessage::New(::google::protobuf::Arena* arena) const {
  ReduceTaskResponseMessage* n = new ReduceTaskResponseMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReduceTaskResponseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ReduceTaskResponseMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ReduceTaskResponseMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, status__);

#undef ZR_HELPER_
#undef ZR_

}

bool ReduceTaskResponseMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_status_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Status status_ = 3;
      case 3: {
        if (tag == 24) {
         parse_status_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status_(static_cast< ::Imagine_MapReduce::Internal::Status >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  return false;
#undef DO_
}

void ReduceTaskResponseMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->status_(), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
}

::google::protobuf::uint8* ReduceTaskResponseMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->status_(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  return target;
}

int ReduceTaskResponseMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status_());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReduceTaskResponseMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReduceTaskResponseMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReduceTaskResponseMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
    MergeFrom(*source);
  }
}

void ReduceTaskResponseMessage::MergeFrom(const ReduceTaskResponseMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.status_() != 0) {
    set_status_(from.status_());
  }
}

void ReduceTaskResponseMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReduceTaskResponseMessage::CopyFrom(const ReduceTaskResponseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.ReduceTaskResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReduceTaskResponseMessage::IsInitialized() const {

  return true;
}

void ReduceTaskResponseMessage::Swap(ReduceTaskResponseMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReduceTaskResponseMessage::InternalSwap(ReduceTaskResponseMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  std::swap(status__, other->status__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReduceTaskResponseMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReduceTaskResponseMessage_descriptor_;
  metadata.reflection = ReduceTaskResponseMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReduceTaskResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void ReduceTaskResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity ReduceTaskResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void ReduceTaskResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void ReduceTaskResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity ReduceTaskResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void ReduceTaskResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
void ReduceTaskResponseMessage::clear_status_() {
  status__ = 0;
}
 ::Imagine_MapReduce::Internal::Status ReduceTaskResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
 void ReduceTaskResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.ReduceTaskResponseMessage.status_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)
