// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartReduceMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Imagine_MapReduce/StartReduceMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Imagine_MapReduce {
namespace Internal {

namespace {

const ::google::protobuf::Descriptor* StartReduceRequestMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StartReduceRequestMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* StartReduceResponseMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StartReduceResponseMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_StartReduceMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_StartReduceMessage_2eproto() {
  protobuf_AddDesc_StartReduceMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "StartReduceMessage.proto");
  GOOGLE_CHECK(file != NULL);
  StartReduceRequestMessage_descriptor_ = file->message_type(0);
  static const int StartReduceRequestMessage_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, listen_ip__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, listen_port__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, file_list__),
  };
  StartReduceRequestMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      StartReduceRequestMessage_descriptor_,
      StartReduceRequestMessage::default_instance_,
      StartReduceRequestMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(StartReduceRequestMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceRequestMessage, _is_default_instance_));
  StartReduceResponseMessage_descriptor_ = file->message_type(1);
  static const int StartReduceResponseMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceResponseMessage, send_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceResponseMessage, recv_identity__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceResponseMessage, status__),
  };
  StartReduceResponseMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      StartReduceResponseMessage_descriptor_,
      StartReduceResponseMessage::default_instance_,
      StartReduceResponseMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(StartReduceResponseMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceResponseMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StartReduceResponseMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_StartReduceMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      StartReduceRequestMessage_descriptor_, &StartReduceRequestMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      StartReduceResponseMessage_descriptor_, &StartReduceResponseMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_StartReduceMessage_2eproto() {
  delete StartReduceRequestMessage::default_instance_;
  delete StartReduceRequestMessage_reflection_;
  delete StartReduceResponseMessage::default_instance_;
  delete StartReduceResponseMessage_reflection_;
}

void protobuf_AddDesc_StartReduceMessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_StartReduceMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Imagine_MapReduce::Internal::protobuf_AddDesc_InternalType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030StartReduceMessage.proto\022\032Imagine_MapR"
    "educe.Internal\032\022InternalType.proto\"\325\001\n\031S"
    "tartReduceRequestMessage\022<\n\016send_identit"
    "y_\030\001 \001(\0162$.Imagine_MapReduce.Internal.Id"
    "entity\022<\n\016recv_identity_\030\002 \001(\0162$.Imagine"
    "_MapReduce.Internal.Identity\022\022\n\nlisten_i"
    "p_\030\003 \001(\t\022\024\n\014listen_port_\030\004 \001(\t\022\022\n\nfile_l"
    "ist_\030\005 \003(\t\"\315\001\n\032StartReduceResponseMessag"
    "e\022<\n\016send_identity_\030\001 \001(\0162$.Imagine_MapR"
    "educe.Internal.Identity\022<\n\016recv_identity"
    "_\030\002 \001(\0162$.Imagine_MapReduce.Internal.Ide"
    "ntity\0223\n\007status_\030\003 \001(\0162\".Imagine_MapRedu"
    "ce.Internal.Statusb\006proto3", 506);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StartReduceMessage.proto", &protobuf_RegisterTypes);
  StartReduceRequestMessage::default_instance_ = new StartReduceRequestMessage();
  StartReduceResponseMessage::default_instance_ = new StartReduceResponseMessage();
  StartReduceRequestMessage::default_instance_->InitAsDefaultInstance();
  StartReduceResponseMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_StartReduceMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_StartReduceMessage_2eproto {
  StaticDescriptorInitializer_StartReduceMessage_2eproto() {
    protobuf_AddDesc_StartReduceMessage_2eproto();
  }
} static_descriptor_initializer_StartReduceMessage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StartReduceRequestMessage::kSendIdentityFieldNumber;
const int StartReduceRequestMessage::kRecvIdentityFieldNumber;
const int StartReduceRequestMessage::kListenIpFieldNumber;
const int StartReduceRequestMessage::kListenPortFieldNumber;
const int StartReduceRequestMessage::kFileListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StartReduceRequestMessage::StartReduceRequestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.StartReduceRequestMessage)
}

void StartReduceRequestMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

StartReduceRequestMessage::StartReduceRequestMessage(const StartReduceRequestMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.StartReduceRequestMessage)
}

void StartReduceRequestMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  listen_ip__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

StartReduceRequestMessage::~StartReduceRequestMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  SharedDtor();
}

void StartReduceRequestMessage::SharedDtor() {
  listen_ip__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void StartReduceRequestMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StartReduceRequestMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StartReduceRequestMessage_descriptor_;
}

const StartReduceRequestMessage& StartReduceRequestMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StartReduceMessage_2eproto();
  return *default_instance_;
}

StartReduceRequestMessage* StartReduceRequestMessage::default_instance_ = NULL;

StartReduceRequestMessage* StartReduceRequestMessage::New(::google::protobuf::Arena* arena) const {
  StartReduceRequestMessage* n = new StartReduceRequestMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StartReduceRequestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(StartReduceRequestMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<StartReduceRequestMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, recv_identity__);
  listen_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  listen_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

  file_list__.Clear();
}

bool StartReduceRequestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_listen_ip_;
        break;
      }

      // optional string listen_ip_ = 3;
      case 3: {
        if (tag == 26) {
         parse_listen_ip_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_listen_ip_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->listen_ip_().data(), this->listen_ip_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_listen_port_;
        break;
      }

      // optional string listen_port_ = 4;
      case 4: {
        if (tag == 34) {
         parse_listen_port_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_listen_port_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->listen_port_().data(), this->listen_port_().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_file_list_;
        break;
      }

      // repeated string file_list_ = 5;
      case 5: {
        if (tag == 42) {
         parse_file_list_:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_file_list_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file_list_(this->file_list__size() - 1).data(),
            this->file_list_(this->file_list__size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_file_list_;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  return false;
#undef DO_
}

void StartReduceRequestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional string listen_ip_ = 3;
  if (this->listen_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_ip_().data(), this->listen_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->listen_ip_(), output);
  }

  // optional string listen_port_ = 4;
  if (this->listen_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_port_().data(), this->listen_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->listen_port_(), output);
  }

  // repeated string file_list_ = 5;
  for (int i = 0; i < this->file_list__size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_list_(i).data(), this->file_list_(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->file_list_(i), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.StartReduceRequestMessage)
}

::google::protobuf::uint8* StartReduceRequestMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional string listen_ip_ = 3;
  if (this->listen_ip_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_ip_().data(), this->listen_ip_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->listen_ip_(), target);
  }

  // optional string listen_port_ = 4;
  if (this->listen_port_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->listen_port_().data(), this->listen_port_().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->listen_port_(), target);
  }

  // repeated string file_list_ = 5;
  for (int i = 0; i < this->file_list__size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file_list_(i).data(), this->file_list_(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->file_list_(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  return target;
}

int StartReduceRequestMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional string listen_ip_ = 3;
  if (this->listen_ip_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->listen_ip_());
  }

  // optional string listen_port_ = 4;
  if (this->listen_port_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->listen_port_());
  }

  // repeated string file_list_ = 5;
  total_size += 1 * this->file_list__size();
  for (int i = 0; i < this->file_list__size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->file_list_(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StartReduceRequestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const StartReduceRequestMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const StartReduceRequestMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.StartReduceRequestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.StartReduceRequestMessage)
    MergeFrom(*source);
  }
}

void StartReduceRequestMessage::MergeFrom(const StartReduceRequestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  file_list__.MergeFrom(from.file_list__);
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.listen_ip_().size() > 0) {

    listen_ip__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.listen_ip__);
  }
  if (from.listen_port_().size() > 0) {

    listen_port__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.listen_port__);
  }
}

void StartReduceRequestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StartReduceRequestMessage::CopyFrom(const StartReduceRequestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.StartReduceRequestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartReduceRequestMessage::IsInitialized() const {

  return true;
}

void StartReduceRequestMessage::Swap(StartReduceRequestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StartReduceRequestMessage::InternalSwap(StartReduceRequestMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  listen_ip__.Swap(&other->listen_ip__);
  listen_port__.Swap(&other->listen_port__);
  file_list__.UnsafeArenaSwap(&other->file_list__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StartReduceRequestMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StartReduceRequestMessage_descriptor_;
  metadata.reflection = StartReduceRequestMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StartReduceRequestMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void StartReduceRequestMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity StartReduceRequestMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void StartReduceRequestMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void StartReduceRequestMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity StartReduceRequestMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void StartReduceRequestMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.recv_identity_)
}

// optional string listen_ip_ = 3;
void StartReduceRequestMessage::clear_listen_ip_() {
  listen_ip__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StartReduceRequestMessage::listen_ip_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  return listen_ip__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StartReduceRequestMessage::set_listen_ip_(const ::std::string& value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
 void StartReduceRequestMessage::set_listen_ip_(const char* value) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
 void StartReduceRequestMessage::set_listen_ip_(const char* value, size_t size) {
  
  listen_ip__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}
 ::std::string* StartReduceRequestMessage::mutable_listen_ip_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  return listen_ip__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StartReduceRequestMessage::release_listen_ip_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
  
  return listen_ip__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StartReduceRequestMessage::set_allocated_listen_ip_(::std::string* listen_ip_) {
  if (listen_ip_ != NULL) {
    
  } else {
    
  }
  listen_ip__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_ip_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_ip_)
}

// optional string listen_port_ = 4;
void StartReduceRequestMessage::clear_listen_port_() {
  listen_port__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& StartReduceRequestMessage::listen_port_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  return listen_port__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StartReduceRequestMessage::set_listen_port_(const ::std::string& value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
 void StartReduceRequestMessage::set_listen_port_(const char* value) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
 void StartReduceRequestMessage::set_listen_port_(const char* value, size_t size) {
  
  listen_port__.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}
 ::std::string* StartReduceRequestMessage::mutable_listen_port_() {
  
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  return listen_port__.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* StartReduceRequestMessage::release_listen_port_() {
  // @@protoc_insertion_point(field_release:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
  
  return listen_port__.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void StartReduceRequestMessage::set_allocated_listen_port_(::std::string* listen_port_) {
  if (listen_port_ != NULL) {
    
  } else {
    
  }
  listen_port__.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), listen_port_);
  // @@protoc_insertion_point(field_set_allocated:Imagine_MapReduce.Internal.StartReduceRequestMessage.listen_port_)
}

// repeated string file_list_ = 5;
int StartReduceRequestMessage::file_list__size() const {
  return file_list__.size();
}
void StartReduceRequestMessage::clear_file_list_() {
  file_list__.Clear();
}
 const ::std::string& StartReduceRequestMessage::file_list_(int index) const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Get(index);
}
 ::std::string* StartReduceRequestMessage::mutable_file_list_(int index) {
  // @@protoc_insertion_point(field_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Mutable(index);
}
 void StartReduceRequestMessage::set_file_list_(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  file_list__.Mutable(index)->assign(value);
}
 void StartReduceRequestMessage::set_file_list_(int index, const char* value) {
  file_list__.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
 void StartReduceRequestMessage::set_file_list_(int index, const char* value, size_t size) {
  file_list__.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
 ::std::string* StartReduceRequestMessage::add_file_list_() {
  // @@protoc_insertion_point(field_add_mutable:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__.Add();
}
 void StartReduceRequestMessage::add_file_list_(const ::std::string& value) {
  file_list__.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
 void StartReduceRequestMessage::add_file_list_(const char* value) {
  file_list__.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
 void StartReduceRequestMessage::add_file_list_(const char* value, size_t size) {
  file_list__.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
StartReduceRequestMessage::file_list_() const {
  // @@protoc_insertion_point(field_list:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return file_list__;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
StartReduceRequestMessage::mutable_file_list_() {
  // @@protoc_insertion_point(field_mutable_list:Imagine_MapReduce.Internal.StartReduceRequestMessage.file_list_)
  return &file_list__;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StartReduceResponseMessage::kSendIdentityFieldNumber;
const int StartReduceResponseMessage::kRecvIdentityFieldNumber;
const int StartReduceResponseMessage::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StartReduceResponseMessage::StartReduceResponseMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Imagine_MapReduce.Internal.StartReduceResponseMessage)
}

void StartReduceResponseMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

StartReduceResponseMessage::StartReduceResponseMessage(const StartReduceResponseMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Imagine_MapReduce.Internal.StartReduceResponseMessage)
}

void StartReduceResponseMessage::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  send_identity__ = 0;
  recv_identity__ = 0;
  status__ = 0;
}

StartReduceResponseMessage::~StartReduceResponseMessage() {
  // @@protoc_insertion_point(destructor:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  SharedDtor();
}

void StartReduceResponseMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StartReduceResponseMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StartReduceResponseMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StartReduceResponseMessage_descriptor_;
}

const StartReduceResponseMessage& StartReduceResponseMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StartReduceMessage_2eproto();
  return *default_instance_;
}

StartReduceResponseMessage* StartReduceResponseMessage::default_instance_ = NULL;

StartReduceResponseMessage* StartReduceResponseMessage::New(::google::protobuf::Arena* arena) const {
  StartReduceResponseMessage* n = new StartReduceResponseMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void StartReduceResponseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(StartReduceResponseMessage, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<StartReduceResponseMessage*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_identity__, status__);

#undef ZR_HELPER_
#undef ZR_

}

bool StartReduceResponseMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_send_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_recv_identity_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
      case 2: {
        if (tag == 16) {
         parse_recv_identity_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_recv_identity_(static_cast< ::Imagine_MapReduce::Internal::Identity >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_status_;
        break;
      }

      // optional .Imagine_MapReduce.Internal.Status status_ = 3;
      case 3: {
        if (tag == 24) {
         parse_status_:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status_(static_cast< ::Imagine_MapReduce::Internal::Status >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  return false;
#undef DO_
}

void StartReduceResponseMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->send_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->recv_identity_(), output);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->status_(), output);
  }

  // @@protoc_insertion_point(serialize_end:Imagine_MapReduce.Internal.StartReduceResponseMessage)
}

::google::protobuf::uint8* StartReduceResponseMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->send_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->recv_identity_(), target);
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->status_(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  return target;
}

int StartReduceResponseMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  int total_size = 0;

  // optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
  if (this->send_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->send_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
  if (this->recv_identity_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->recv_identity_());
  }

  // optional .Imagine_MapReduce.Internal.Status status_ = 3;
  if (this->status_() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status_());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StartReduceResponseMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const StartReduceResponseMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const StartReduceResponseMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Imagine_MapReduce.Internal.StartReduceResponseMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Imagine_MapReduce.Internal.StartReduceResponseMessage)
    MergeFrom(*source);
  }
}

void StartReduceResponseMessage::MergeFrom(const StartReduceResponseMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.send_identity_() != 0) {
    set_send_identity_(from.send_identity_());
  }
  if (from.recv_identity_() != 0) {
    set_recv_identity_(from.recv_identity_());
  }
  if (from.status_() != 0) {
    set_status_(from.status_());
  }
}

void StartReduceResponseMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StartReduceResponseMessage::CopyFrom(const StartReduceResponseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Imagine_MapReduce.Internal.StartReduceResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartReduceResponseMessage::IsInitialized() const {

  return true;
}

void StartReduceResponseMessage::Swap(StartReduceResponseMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StartReduceResponseMessage::InternalSwap(StartReduceResponseMessage* other) {
  std::swap(send_identity__, other->send_identity__);
  std::swap(recv_identity__, other->recv_identity__);
  std::swap(status__, other->status__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata StartReduceResponseMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StartReduceResponseMessage_descriptor_;
  metadata.reflection = StartReduceResponseMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// StartReduceResponseMessage

// optional .Imagine_MapReduce.Internal.Identity send_identity_ = 1;
void StartReduceResponseMessage::clear_send_identity_() {
  send_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity StartReduceResponseMessage::send_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.send_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(send_identity__);
}
 void StartReduceResponseMessage::set_send_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  send_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.send_identity_)
}

// optional .Imagine_MapReduce.Internal.Identity recv_identity_ = 2;
void StartReduceResponseMessage::clear_recv_identity_() {
  recv_identity__ = 0;
}
 ::Imagine_MapReduce::Internal::Identity StartReduceResponseMessage::recv_identity_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.recv_identity_)
  return static_cast< ::Imagine_MapReduce::Internal::Identity >(recv_identity__);
}
 void StartReduceResponseMessage::set_recv_identity_(::Imagine_MapReduce::Internal::Identity value) {
  
  recv_identity__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.recv_identity_)
}

// optional .Imagine_MapReduce.Internal.Status status_ = 3;
void StartReduceResponseMessage::clear_status_() {
  status__ = 0;
}
 ::Imagine_MapReduce::Internal::Status StartReduceResponseMessage::status_() const {
  // @@protoc_insertion_point(field_get:Imagine_MapReduce.Internal.StartReduceResponseMessage.status_)
  return static_cast< ::Imagine_MapReduce::Internal::Status >(status__);
}
 void StartReduceResponseMessage::set_status_(::Imagine_MapReduce::Internal::Status value) {
  
  status__ = value;
  // @@protoc_insertion_point(field_set:Imagine_MapReduce.Internal.StartReduceResponseMessage.status_)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Internal
}  // namespace Imagine_MapReduce

// @@protoc_insertion_point(global_scope)
